// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzIzB6TpLc6LtG5sWg4xqpCLO0WA1XiuU',
    appId: '1:327546726754:web:8fc1c959d5a3a93ddf643b',
    messagingSenderId: '327546726754',
    projectId: 'bero-code',
    authDomain: 'bero-code.firebaseapp.com',
    storageBucket: 'bero-code.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHOPthlil6b5ArdiUP3WDOl5Lie8kogGA',
    appId: '1:327546726754:android:bdb0aeccb9a89029df643b',
    messagingSenderId: '327546726754',
    projectId: 'bero-code',
    storageBucket: 'bero-code.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRn7r7Y_NCH2dgpYLZqK55fBA_bz2h-q0',
    appId: '1:327546726754:ios:93403dd9d59b9bdbdf643b',
    messagingSenderId: '327546726754',
    projectId: 'bero-code',
    storageBucket: 'bero-code.appspot.com',
    iosClientId: '327546726754-hf31ekmigmk3fftlsjp8u409kcjf27qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.beroCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRn7r7Y_NCH2dgpYLZqK55fBA_bz2h-q0',
    appId: '1:327546726754:ios:e65ed9cd0040f0ffdf643b',
    messagingSenderId: '327546726754',
    projectId: 'bero-code',
    storageBucket: 'bero-code.appspot.com',
    iosClientId: '327546726754-83e71is5jr6vbu4t78c9t5eca1gkvf1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.beroCode.RunnerTests',
  );
}
